### PR TITLE
prefer token from variable

### PR DESCRIPTION
**Pull request by RekGRpth**

### CODE REVIEW

**Comment by maxam18** [comment]
Cannot accept just now. Authorization should have preference in my case. Will think about.

**Comment by RekGRpth** [comment]
> Authorization should have preference in my case

just not setup variable

**Comment by RekGRpth** [comment]
I want make fake basic auth by
```nginx
 set_secure_random_alphanum $password 8;
 set_encode_base64 $username_password_encode $ejwt_claim:$password;
 more_set_input_headers "Authorization: Basic $username_password_encode";
```
but can not, due to ejwt catch any auth

**Comment by maxam18** [comment]
Hmm. This is the case. 
What if I fallback to variable if that is not Bearer? 
Do you think it would be wise in general?

**Comment by RekGRpth** [comment]
> Hmm. This is the case.
> What if I fallback to variable if that is not Bearer?
> Do you think it would be wise in general?

yes, I agree

**Comment by maxam18** [comment]
Bearer auth check Implemented

**Pull request closed without merging**
